server:
  port: 8990
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATA_BASE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    out-of-order: true
    baseline-on-migrate: true